### ISSUE TITLE
Decimal support is missing

### ISSUE THREAD

**Issue by jpulleman** [mendix/RestServices#62]
Throws an error like this (ID is Mendix decimal attribute):

java.lang.RuntimeException: java.lang.Exception: Unsupported attribute type 'Decimal' in attribute 'ID'
	at restservices.consume.RestConsumer$7.apply(RestConsumer.java:506)
	at restservices.consume.RestConsumer$7.apply(RestConsumer.java:477)
	at restservices.consume.RestConsumer.doRequest(RestConsumer.java:269)
	at restservices.consume.RestConsumer.request(RestConsumer.java:477)
	at restservices.actions.request.executeAction(request.java:45)
	at restservices.actions.request.executeAction(request.java:1)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:53)
	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:291)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:276)
	at com.mendix.core.actionmanagement.ActionManager$1.execute(ActionManager.java:204)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:37)
	at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:199)
	at com.mendix.core.component.InternalCore.execute(InternalCore.java:228)
	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:46)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:49)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:196)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:151)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:53)
	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:291)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:276)
	at com.mendix.core.actionmanagement.ActionManager$1.execute(ActionManager.java:204)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:37)
	at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:199)
	at com.mendix.core.component.InternalCore.execute(InternalCore.java:228)
	at com.mendix.webui.actions.client.ExecuteAction.execute(ExecuteAction.java:135)
	at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply$mcV$sp(ClientRequestHandler.scala:300)
	at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:293)
	at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:293)
	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2$$anon$1.execute(ActionDispatching.scala:151)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:37)
	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(ActionDispatching.scala:153)
	at scala.util.Try$.apply(Try.scala:191)
	at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(ActionDispatching.scala:147)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.mendix.core.session.Worker.aroundReceive(ActionDispatching.scala:140)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Caused by: java.lang.Exception: Unsupported attribute type 'Decimal' in attribute 'ID'
	at restservices.util.JsonDeserializer.jsonAttributeToPrimitive(JsonDeserializer.java:202)
	at restservices.util.JsonDeserializer.readJsonObjectIntoMendixObject(JsonDeserializer.java:138)
	at restservices.util.JsonDeserializer.readJsonDataIntoMendixObject(JsonDeserializer.java:77)
	at restservices.util.JsonDeserializer.readJsonDataIntoMendixObject(JsonDeserializer.java:38)
	at restservices.util.JsonDeserializer.readJsonObjectIntoMendixObject(JsonDeserializer.java:121)
	at restservices.util.JsonDeserializer.readJsonDataIntoMendixObject(JsonDeserializer.java:77)
	at restservices.consume.RestConsumer$7.apply(RestConsumer.java:500)
	at restservices.consume.RestConsumer$7.apply(RestConsumer.java:477)
	at restservices.consume.RestConsumer.doRequest(RestConsumer.java:269)
	at restservices.consume.RestConsumer.request(RestConsumer.java:477)
	at restservices.actions.request.executeAction(request.java:45)
	at restservices.actions.request.executeAction(request.java:1)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:53)
	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:291)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:276)
	at com.mendix.core.actionmanagement.ActionManager$1.execute(ActionManager.java:204)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:37)
	at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:199)
	at com.mendix.core.component.InternalCore.execute(InternalCore.java:228)
	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:46)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:49)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:196)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:151)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:53)
	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:291)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:276)
	at com.mendix.core.actionmanagement.ActionManager$1.execute(ActionManager.java:204)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:37)
	at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:199)
	at com.mendix.core.component.InternalCore.execute(InternalCore.java:228)
	at com.mendix.webui.actions.client.ExecuteAction.execute(ExecuteAction.java:135)
	at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply$mcV$sp(ClientRequestHandler.scala:300)
	at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:293)
	at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:293)
	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2$$anon$1.execute(ActionDispatching.scala:151)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:37)
	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(ActionDispatching.scala:153)
	at scala.util.Try$.apply(Try.scala:191)
	at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(ActionDispatching.scala:147)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.mendix.core.session.Worker.aroundReceive(ActionDispatching.scala:140)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by mweststrate** [comment]
Published

**Comment by jpulleman** [comment]
Cool, thanks!
